{
 "title": "Desire6g",
 "time": { "from": "now-12s", "to": "now-2s" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "gold_portrange_min", "label": "Gold portrange min", "query": "20000" },
   { "name": "gold_portrange_max", "label": "Gold portrange max", "query": "21999" },
   { "name": "silver_portrange_min", "label": "Silver portrange min", "query": "22000" },
   { "name": "silver_portrange_max", "label": "Silver portrange max", "query": "29999" },
   { "name": "flowcount", "label": "Flow count", "query": "10" }
  ]
 },
 "panels": [
  {
   "title": "Per flow throughput(First N flow)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps", "label": "Mbps" }
   ],
   "targets": [
    {
     "alias": "Gold_hide",
     "groupBy": [
      { "params": [ "flow_id" ], "type": "tag" }
     ],
     "measurement": "udpStats",
     "query": "SELECT \"value\"  *8 FROM \"udpStats\" WHERE (\"port_id\" >= ${gold_portrange_min} AND flow_id<>'20000' AND \"port_id\" < ${gold_portrange_min}+${flowcount}) AND $timeFilter GROUP BY \"flow_id\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ " *8" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Gold ",
     "groupBy": [
      { "params": [ "flow_id" ], "type": "tag" }
     ],
     "measurement": "udpStats",
     "query": "SELECT \"value\"  *8 FROM \"udpStats\" WHERE (\"port_id\" >= ${gold_portrange_min} AND flow_id='20000' AND \"port_id\" < ${gold_portrange_min}+${flowcount}) AND $timeFilter GROUP BY \"flow_id\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ " *8" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Silver_hide",
     "groupBy": [
      { "params": [ "flow_id" ], "type": "tag" }
     ],
     "measurement": "udpStats",
     "query": "SELECT \"value\"  *8 FROM \"udpStats\" WHERE (\"port_id\" >= ${silver_portrange_min} AND flow_id<>'22000'  AND \"port_id\" < ${silver_portrange_min}+${flowcount}) AND $timeFilter GROUP BY \"flow_id\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ " *8" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Silver ",
     "groupBy": [
      { "params": [ "flow_id" ], "type": "tag" }
     ],
     "measurement": "udpStats",
     "query": "SELECT \"value\"  *8 FROM \"udpStats\" WHERE (\"port_id\" >= ${silver_portrange_min} AND flow_id='22000'  AND \"port_id\" < ${silver_portrange_min}+${flowcount}) AND $timeFilter GROUP BY \"flow_id\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ " *8" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "$tag_flow_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"thr\" FROM \"thr_pp\" WHERE $timeFilter GROUP BY \"flow_id\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg/Min/Max throughput",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bps", "label": "Mbps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" }
     ],
     "measurement": "udpStats",
     "query": "SELECT max(\"value\") *8 as \"Gold Max\", mean(\"value\") *8 as \"Gold Avg\", min(\"value\") *8 as \"Gold Min\" FROM \"udpStats\" WHERE (\"port_id\" >= ${gold_portrange_min} AND \"port_id\" <= ${gold_portrange_max}) AND $timeFilter GROUP BY time(1s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "port_id", "operator": ">", "value": "${portrange_min}" },
      { "condition": "AND", "key": "port_id", "operator": "<", "value": "${portrange_max}" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" }
     ],
     "measurement": "udpStats",
     "query": "SELECT max(\"value\") *8 as \"Silver Max\", mean(\"value\") *8 as \"Silver Avg\", min(\"value\") *8 as \"Silver Min\"  FROM \"udpStats\" WHERE (\"port_id\" >= ${silver_portrange_min} AND \"port_id\" <= ${silver_portrange_max}) AND $timeFilter GROUP BY time(1s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "port_id", "operator": ">", "value": "${portrange_min}" },
      { "condition": "AND", "key": "port_id", "operator": "<", "value": "${portrange_max}" }
     ]
    }
   ]
  },
  {
   "title": "Drop rate in AQM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "alias": "Classic Drop",
     "measurement": "ecn_drop_percent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "flow_id", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Loss Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "Cubic $tag_flow_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\"  FROM \"lossCubic\" WHERE $timeFilter GROUP BY \"flow_id\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "UDP $tag_flow_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "flow_id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "loss_pp",
     "select": [
      [
       { "params": [ "loss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gold flows",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "flow_id" ], "type": "tag" }
     ],
     "measurement": "flownumPP",
     "query": "SELECT count(distinct \"port_id\") FROM \"udpStats\" WHERE (\"port_id\" >= ${gold_portrange_min} AND \"port_id\" <= ${gold_portrange_max}) AND \"value\">0 AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Silver flows",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_flow_id",
     "groupBy": [
      { "params": [ "flow_id" ], "type": "tag" }
     ],
     "measurement": "flownumPP",
     "query": "SELECT count(distinct \"port_id\")  FROM \"udpStats\" WHERE (\"port_id\" >= ${silver_portrange_min} AND \"port_id\" <= ${silver_portrange_max}) AND \"value\">0 AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bps", "label": "Mbps" }
   ],
   "targets": [
    {
     "alias": "Gold",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" }
     ],
     "measurement": "udpStats",
     "query": "SELECT sum(\"value\")  *8 FROM \"udpStats\" WHERE (\"port_id\" >= ${gold_portrange_min} AND \"port_id\" <= ${gold_portrange_max}) AND $timeFilter GROUP BY time(1s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " *8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "port_id", "operator": ">", "value": "${portrange_min}" },
      { "condition": "AND", "key": "port_id", "operator": "<", "value": "${portrange_max}" }
     ]
    },
    {
     "alias": "Silver",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" }
     ],
     "measurement": "udpStats",
     "query": "SELECT sum(\"value\")  *8 FROM \"udpStats\" WHERE (\"port_id\" >= ${silver_portrange_min} AND \"port_id\" <= ${silver_portrange_max}) AND $timeFilter GROUP BY time(1s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " *8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "port_id", "operator": ">", "value": "${portrange_min}" },
      { "condition": "AND", "key": "port_id", "operator": "<", "value": "${portrange_max}" }
     ]
    }
   ]
  },
  {
   "title": "In/Out Thr ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bps", "label": "Mbps" }
   ],
   "targets": [
    {
     "alias": "$tag_flow_id",
     "groupBy": [
      { "params": [ "flow_id" ], "type": "tag" }
     ],
     "measurement": "in_cl_l4s",
     "query": "SELECT \"value\" FROM \"timeseries_thr\" WHERE $timeFilter GROUP BY \"flow_id\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "o_$tag_flow_id",
     "groupBy": [
      { "params": [ "flow_id" ], "type": "tag" }
     ],
     "measurement": "out_cl_l4s",
     "query": "SELECT \"value\" FROM \"timeseries_thr\" WHERE $timeFilter GROUP BY \"flow_id\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CTV",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "CTV Classic (max)",
     "groupBy": [
      { "params": [ "flow_id" ], "type": "tag" }
     ],
     "measurement": "max_ctv",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "flow_id", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "CTV Classic (min)",
     "groupBy": [
      { "params": [ "flow_id" ], "type": "tag" }
     ],
     "measurement": "min_ctv",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "flow_id", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Physical qlen",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "alias": "pkt_delay_$tag_flow_id",
     "groupBy": [
      { "params": [ "flow_id" ], "type": "tag" }
     ],
     "measurement": "pkt_delay",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "flow_id", "operator": "=", "value": "cl" }
     ]
    }
   ]
  },
  {
   "title": "Ping delay",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" },
       { "params": [ "-0" ], "type": "math" }
      ]
     ]
    }
   ]
  }
 ]
}